<a href="https://colab.research.google.com/github/bradencruzzz/day72-pandas-college-major-analysis/blob/main/day72_pandas_college_major_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
df = pd.read_csv('/salaries_by_college_major.csv')

In [ ]:
df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business

In [ ]:
df.shape

(51, 6)

In [ ]:
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

In [ ]:
df.isna()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
5,False,False,False,False,False,False
6,False,False,False,False,False,False
7,False,False,False,False,False,False
8,False,False,False,False,False,False
9,False,False,False,False,False,False
10,False,False,False,False,False,False
11,False,False,False,False,False,False
12,False,False,False,False,False,False
13,False,False,False,False,False,False
14,False,False,False,False,False,False
15,False,False,False,False,False,False
16,False,False,False,False,False,False
17,False,False,False,False,False,False
18,False,False,False,False,False,False
19,False,False,False,False,False,False
20,False,False,False,False,False,False
21,False,False,False,False,False,False
22,False,False,False,False,False,False
23,False,False,False,False,False,False
24,False,False,False,False,False,False
25,False,False,False,False,False,False
26,False,False,False,False,False,False
27,False,False,False,False,False,False
28,False,False,False,False,False,False
29,False,False,False,False,False,False
30,False,False,False,False,False,False
31,False,False,False,False,False,False
32,False,False,False,False,False,False
33,False,False,False,False,False,False
34,False,False,False,False,False,False
35,False,False,False,False,False,False
36,False,False,False,False,False,False
37,False,False,False,False,False,False
38,False,False,False,False,False,False
39,False,False,False,False,False,False
40,False,False,False,False,False,False
41,False,False,False,False,False,False
42,False,False,False,False,False,False
43,False,False,False,False,False,False
44,False,False,False,False,False,False
45,False,False,False,False,False,False
46,False,False,False,False,False,False
47,False,False,False,False,False,False
48,False,False,False,False,False,False
49,False,False,False,False,False,False
50,False,True,True,True,True,True

In [ ]:
clean_df = df.dropna()
clean_df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

In [ ]:
# Highest Starting Salary Major
clean_df['Starting Median Salary']

0     46000.0
1     57700.0
2     42600.0
3     36800.0
4     41600.0
5     35800.0
6     38800.0
7     43000.0
8     63200.0
9     42600.0
10    53900.0
11    38100.0
12    61400.0
13    55900.0
14    53700.0
15    35000.0
16    35900.0
17    50100.0
18    34900.0
19    60900.0
20    38000.0
21    37900.0
22    47900.0
23    39100.0
24    41200.0
25    43500.0
26    35700.0
27    38800.0
28    39200.0
29    37800.0
30    57700.0
31    49100.0
32    36100.0
33    40900.0
34    35600.0
35    49200.0
36    40800.0
37    45400.0
38    57900.0
39    35900.0
40    54200.0
41    39900.0
42    39900.0
43    74300.0
44    50300.0
45    40800.0
46    35900.0
47    34100.0
48    36500.0
49    34000.0
Name: Starting Median Salary, dtype: float64

In [ ]:
clean_df['Starting Median Salary'].max()

74300.0

In [ ]:
clean_df['Starting Median Salary'].idxmax()

np.int64(43)

In [ ]:
clean_df['Undergraduate Major'].loc[43]

'Physician Assistant'

In [ ]:
clean_df['Undergraduate Major'][43]

'Physician Assistant'

In [ ]:
clean_df.loc[43]

Undergraduate Major                  Physician Assistant
Starting Median Salary                           74300.0
Mid-Career Median Salary                         91700.0
Mid-Career 10th Percentile Salary                66400.0
Mid-Career 90th Percentile Salary               124000.0
Group                                               STEM
Name: 43, dtype: object

In [ ]:
# Highest Mid-Career Salary

clean_df['Mid-Career Median Salary'].max()

107000.0

In [ ]:
clean_df['Mid-Career Median Salary'].idxmax()

np.int64(8)

In [ ]:
clean_df.loc[8]

Undergraduate Major                  Chemical Engineering
Starting Median Salary                            63200.0
Mid-Career Median Salary                         107000.0
Mid-Career 10th Percentile Salary                 71900.0
Mid-Career 90th Percentile Salary                194000.0
Group                                                STEM
Name: 8, dtype: object

In [ ]:
# Lowest Starting Salary College Major
clean_df['Starting Median Salary'].min()

34000.0

In [ ]:
clean_df.loc[clean_df['Starting Median Salary'].idxmin()]

Undergraduate Major                  Spanish
Starting Median Salary               34000.0
Mid-Career Median Salary             53100.0
Mid-Career 10th Percentile Salary    31000.0
Mid-Career 90th Percentile Salary    96400.0
Group                                   HASS
Name: 49, dtype: object

In [ ]:
# Lowest Mid-Career Salary
clean_df['Mid-Career Median Salary'].min()

52000.0

In [ ]:
clean_df.loc[clean_df['Mid-Career Median Salary'].idxmin()]

Undergraduate Major                  Education
Starting Median Salary                 34900.0
Mid-Career Median Salary               52000.0
Mid-Career 10th Percentile Salary      29300.0
Mid-Career 90th Percentile Salary     102000.0
Group                                     HASS
Name: 18, dtype: object

In [ ]:
# Lowest Risk Major
gap = clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']
print(gap)

0     109800.0
1      96700.0
2     113700.0
3     104200.0
4      85400.0
5      96200.0
6      98100.0
7     108200.0
8     122100.0
9     102700.0
10     84600.0
11    105500.0
12     95900.0
13     98000.0
14    114700.0
15     74800.0
16    116300.0
17    159400.0
18     72700.0
19     98700.0
20     99600.0
21    102100.0
22    147800.0
23     70000.0
24     92000.0
25    111000.0
26     76000.0
27     66400.0
28    112000.0
29     88500.0
30    115900.0
31     84500.0
32     71300.0
33    118800.0
34    106600.0
35    100700.0
36    132900.0
37    137800.0
38     99300.0
39    107300.0
40     50700.0
41     65300.0
42    132500.0
43     57600.0
44    122000.0
45    126800.0
46     95400.0
47     66700.0
48     87300.0
49     65400.0
dtype: float64

In [ ]:
spread_col = clean_df['Mid-Career 90th Percentile Salary'].subtract(clean_df['Mid-Career 10th Percentile Salary'])
clean_df.insert(1, 'Spread', spread_col)
clean_df.head()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,109800.0,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,96700.0,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,113700.0,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,104200.0,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,85400.0,41600.0,76800.0,50600.0,136000.0,Business

In [ ]:
lowest_spread = clean_df.sort_values('Spread')
lowest_spread[['Undergraduate Major', 'Spread']].head()

           Undergraduate Major   Spread
40                     Nursing  50700.0
43         Physician Assistant  57600.0
41                   Nutrition  65300.0
49                     Spanish  65400.0
27  Health Care Administration  66400.0

In [ ]:
# Highest Potential
highest_mid_90 = clean_df.sort_values('Mid-Career 90th Percentile Salary', ascending=False)
highest_mid_90[['Undergraduate Major', 'Mid-Career 90th Percentile Salary']].head()

     Undergraduate Major  Mid-Career 90th Percentile Salary
17             Economics                           210000.0
22               Finance                           195000.0
8   Chemical Engineering                           194000.0
37                  Math                           183000.0
44               Physics                           178000.0

In [ ]:
# Highest risk/spread
highest_spread = clean_df.sort_values('Spread', ascending=False)
highest_spread[['Undergraduate Major', 'Spread']].head()

   Undergraduate Major    Spread
17           Economics  159400.0
22             Finance  147800.0
37                Math  137800.0
36           Marketing  132900.0
42          Philosophy  132500.0

In [ ]:
# Highest Mid-Career Earning
highest_spread = clean_df.sort_values('Mid-Career Median Salary', ascending=False)
highest_spread[['Undergraduate Major', 'Mid-Career Median Salary']].head()

       Undergraduate Major  Mid-Career Median Salary
8     Chemical Engineering                  107000.0
12    Computer Engineering                  105000.0
19  Electrical Engineering                  103000.0
1    Aerospace Engineering                  101000.0
17               Economics                   98600.0

In [ ]:
# Group By STEM, Business, HASS
clean_df.groupby('Group')['Undergraduate Major'].count().sort_values(ascending=False)

Group
HASS        22
STEM        16
Business    12
Name: Undergraduate Major, dtype: int64

In [ ]:
pd.options.display.float_format = '{:,.2f}'.format
clean_df.groupby('Group')[['Starting Median Salary', 'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary', 'Mid-Career 90th Percentile Salary', 'Spread']].mean().sort_values('Mid-Career Median Salary', ascending=False)

,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Spread
Group,,,,,
STEM,"53,862.50","90,812.50","56,025.00","157,625.00","101,600.00"
Business,"44,633.33","75,083.33","43,566.67","147,525.00","103,958.33"
HASS,"37,186.36","62,968.18","34,145.45","129,363.64","95,218.18"